kind = "web"
previewPath = "/"
title = "Fire Detector"
version = "1.0.0"
id = "artifacts/fire-detector"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22178

[services.development]
run = "pnpm --filter @workspace/fire-detector run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fire-detector", "run", "build" ]
publicDir = "artifacts/fire-detector/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22178"
BASE_PATH = "/"
